/* Planar linkage synthesis, millimetres and radians. */
(function(root){'use strict';
const PI=Math.PI,TAU=2*PI,EPS=1e-8;
const add=(a,b)=>[a[0]+b[0],a[1]+b[1]],sub=(a,b)=>[a[0]-b[0],a[1]-b[1]],mul=(a,s)=>[a[0]*s,a[1]*s];
const dot=(a,b)=>a[0]*b[0]+a[1]*b[1],cross=(a,b)=>a[0]*b[1]-a[1]*b[0],len=a=>Math.hypot(a[0],a[1]);
const rot=(p,t)=>[p[0]*Math.cos(t)-p[1]*Math.sin(t),p[0]*Math.sin(t)+p[1]*Math.cos(t)];
const dist=(a,b)=>len(sub(a,b)),angle=p=>Math.atan2(p[1],p[0]),wrap=t=>Math.atan2(Math.sin(t),Math.cos(t));
const pose=(p,c)=>add(rot(p,c.angle*PI/180),[c.dx,c.dy]);
const closest=(pair,p)=>dist(pair[0],p)<=dist(pair[1],p)?pair[0]:pair[1];
function intersections(a,ra,b,rb){const d=dist(a,b);if(d<EPS||d>ra+rb+1e-7||d<Math.abs(ra-rb)-1e-7)return null;
 const v=mul(sub(b,a),1/d),along=(ra*ra-rb*rb+d*d)/(2*d),h2=ra*ra-along*along;if(h2<-1e-6)return null;
 const m=add(a,mul(v,along)),o=mul([-v[1],v[0]],Math.sqrt(Math.max(0,h2)));return [add(m,o),sub(m,o)];}
function bisector(target,p,c){const next=pose(p,c),n=sub(next,p),d=dot(n,n);if(d<EPS)return null;const midpoint=mul(add(p,next),.5);return add(target,mul(n,dot(sub(midpoint,target),n)/d));}
function inZone(p,z){return !!p&&dist(p,z.target)<=z.radius+1e-7;}
function samp(z,f,rng){const a=TAU*rng(),radius=z.radius*Math.sqrt(f)*Math.sqrt(rng());return add(z.target,[radius*Math.cos(a),radius*Math.sin(a)]);}
function scoreTargets(points,zones){let score=0;for(const key of Object.keys(zones)){const z=zones[key];if(!points[key]||!inZone(points[key],z))return Infinity;score+=Math.pow(dist(points[key],z.target)/Math.max(z.radius,1),2);}return score;}
function checkLengths(pairs,c){for(const [a,b] of pairs){const l=dist(a,b);if(l<c.minLength||l>c.maxLength||!Number.isFinite(l))return false;}return true;}
function bodyAt(pos,ang,c){const {x,y,width,height}=c.body;return [[x,y],[x+width,y],[x+width,y+height],[x,y+height]].map(p=>add(rot(p,ang),pos));}
function orient(a,b,c){return cross(sub(b,a),sub(c,a));}function edges(poly){return poly.map((p,i)=>[p,poly[(i+1)%poly.length]]);}
function onSeg(a,b,p){return Math.min(a[0],b[0])-EPS<=p[0]&&p[0]<=Math.max(a[0],b[0])+EPS&&Math.min(a[1],b[1])-EPS<=p[1]&&p[1]<=Math.max(a[1],b[1])+EPS;}
function hitSeg(a,b,c,d){const o1=orient(a,b,c),o2=orient(a,b,d),o3=orient(c,d,a),o4=orient(c,d,b);return (o1*o2<-EPS&&o3*o4<-EPS)||(Math.abs(o1)<EPS&&onSeg(a,b,c))||(Math.abs(o2)<EPS&&onSeg(a,b,d))||(Math.abs(o3)<EPS&&onSeg(c,d,a))||(Math.abs(o4)<EPS&&onSeg(c,d,b));}
function inPoly(p,poly){let inside=false;for(let i=0,j=poly.length;i<poly.length;j=i++){const a=poly[i],b=poly[j];if(((a[1]>p[1])!==(b[1]>p[1]))&&(p[0]<(b[0]-a[0])*(p[1]-a[1])/(b[1]-a[1])+a[0]))inside=!inside;}return inside;}
function collision(poly,ob){return poly.some(p=>inPoly(p,ob))||ob.some(p=>inPoly(p,poly))||edges(poly).some(([a,b])=>edges(ob).some(([d,e])=>hitSeg(a,b,d,e)));}
function segmentObstacle(a,b,ob){return inPoly(a,ob)||inPoly(b,ob)||edges(ob).some(([d,e])=>hitSeg(a,b,d,e));}
function inObstacles(state,c){if(!c.obstacles||!c.obstacles.length)return false;const segs=state.mode===4?[[state.A,state.P],[state.D,state.Q]]:[[state.A,state.B],[state.A,state.E],[state.B,state.E],[state.D,state.C],[state.B,state.C],[state.B,state.P],[state.C,state.P],[state.E,state.Q]];return c.obstacles.some(ob=>collision(state.body,ob)||segs.some(([a,b])=>segmentObstacle(a,b,ob)));}
function gate(states,c){const g=c.gates||{};if(!g.enabled)return true;for(const entry of [g.early,g.mid,g.late]){if(!entry||!entry.enabled)continue;const s=states[Math.round((states.length-1)*entry.fraction)],world=add(rot(c.reference,s.angle),s.translation);const rise=world[1]-c.reference[1],throwX=world[0]-c.reference[0];if(rise<entry.minRise-EPS||rise>entry.maxRise+EPS||throwX<entry.minThrow-EPS||throwX>entry.maxThrow+EPS||Math.abs(s.angle*180/PI)>entry.maxRotation+EPS)return false;}return true;}
function simulate4(p,c,steps=41){const {A,D,P,Q}=p,rAP=dist(A,P),rDQ=dist(D,Q),rPQ=dist(P,Q),theta=wrap(angle(sub(pose(P,c),A))-angle(sub(P,A)));if(Math.abs(theta)<.05)return null;let prior=Q,states=[],minTrans=1;
 for(let i=0;i<steps;i++){const t=i/(steps-1),now=add(A,rot(sub(P,A),theta*t)),pair=intersections(now,rPQ,D,rDQ);if(!pair)return null;const q=closest(pair,prior),ang=wrap(angle(sub(q,now))-angle(sub(Q,P))),translation=sub(now,rot(P,ang));const s={mode:4,fraction:t,angle:ang,translation,body:bodyAt(translation,ang,c),A,D,P:now,Q:q};const tr=Math.abs(cross(sub(q,now),sub(q,D)))/Math.max(EPS,rPQ*rDQ);minTrans=Math.min(minTrans,tr);if(tr<c.minTransmission||inObstacles(s,c))return null;states.push(s);prior=q;}
 const end=states[states.length-1],pError=dist(end.P,pose(P,c)),qError=dist(end.Q,pose(Q,c)),aError=Math.abs(wrap(end.angle-c.angle*PI/180))*180/PI;if(pError>c.poseTolerance||qError>c.poseTolerance||aError>c.angleTolerance||!gate(states,c))return null;return {states,minimumTransmissionDeg:Math.asin(Math.min(1,minTrans))*180/PI,endpointError:Math.max(pError,qError),angleError:aError,inputSweep:theta*180/PI};}
function solve2(M,v){const det=M[0][0]*M[1][1]-M[0][1]*M[1][0];if(Math.abs(det)<.03)return null;return [(v[0]*M[1][1]-M[0][1]*v[1])/det,(M[0][0]*v[1]-v[0]*M[1][0])/det];}
function minusMatrices(a,b){return [[Math.cos(a)-Math.cos(b),-Math.sin(a)+Math.sin(b)],[Math.sin(a)-Math.sin(b),Math.cos(a)-Math.cos(b)]];}
function candidate6(c,pts,alpha,beta,gamma){const {A,D,P,Q}=pts;const t1=sub(A,rot(A,alpha)),t2=sub(D,rot(D,gamma)),t3=sub(pose(P,c),rot(P,beta));const B=solve2(minusMatrices(alpha,beta),sub(t3,t1)),C=solve2(minusMatrices(gamma,beta),sub(t3,t2));if(!B||!C)return null;const q1=pose(Q,c),v=sub(t1,q1),n=mul(add(Q,rot(v,-alpha)),2),n2=dot(n,n);if(n2<EPS)return null;const base=mul(n,(dot(Q,Q)-dot(v,v))/n2),direction=[-n[1]/Math.sqrt(n2),n[0]/Math.sqrt(n2)];const E=add(base,mul(direction,dot(sub(c.zones.E.target,base),direction)));return {A,D,P,Q,B,C,E,alpha,beta,gamma};}
function simulate6(p,c,steps=41){const {A,B,C,D,E,P,Q,alpha}=p;if(!Number.isFinite(alpha)||Math.abs(alpha)<.05)return null;const bc=dist(B,C),dc=dist(D,C),eq=dist(E,Q),pq=dist(P,Q),angBC=angle(sub(C,B)),angPQ=angle(sub(Q,P));let prevC=C,prevQ=Q,states=[],minTrans=1;
 for(let i=0;i<steps;i++){const t=i/(steps-1),b=add(A,rot(sub(B,A),alpha*t)),e=add(A,rot(sub(E,A),alpha*t));const cs=intersections(b,bc,D,dc);if(!cs)return null;const cc=closest(cs,prevC),beta=wrap(angle(sub(cc,b))-angBC),pp=add(b,rot(sub(P,B),beta));const qs=intersections(e,eq,pp,pq);if(!qs)return null;const qq=closest(qs,prevQ),ang=wrap(angle(sub(qq,pp))-angPQ),translation=sub(pp,rot(P,ang));const t1=Math.abs(cross(sub(cc,b),sub(cc,D)))/Math.max(EPS,bc*dc),t2=Math.abs(cross(sub(qq,e),sub(qq,pp)))/Math.max(EPS,eq*pq);minTrans=Math.min(minTrans,t1,t2);const s={mode:6,fraction:t,angle:ang,translation,body:bodyAt(translation,ang,c),A,D,B:b,C:cc,E:e,P:pp,Q:qq};if(minTrans<c.minTransmission||inObstacles(s,c))return null;states.push(s);prevC=cc;prevQ=qq;}
 const end=states[states.length-1],pError=dist(end.P,pose(P,c)),qError=dist(end.Q,pose(Q,c)),aError=Math.abs(wrap(end.angle-c.angle*PI/180))*180/PI;if(pError>c.poseTolerance||qError>c.poseTolerance||aError>c.angleTolerance||!gate(states,c))return null;return {states,minimumTransmissionDeg:Math.asin(Math.min(1,minTrans))*180/PI,endpointError:Math.max(pError,qError),angleError:aError,inputSweep:alpha*180/PI};}
function seedRandom(seed){let a=(seed>>>0)||1;return ()=>{a^=a<<13;a^=a>>>17;a^=a<<5;return (a>>>0)/4294967296;};}
function scoreCandidate(p,sim,c){const distanceScore=scoreTargets(p,c.zones);return distanceScore+2/Math.max(1,sim.minimumTransmissionDeg);}
function candidateAt(c,index,rng){const radius=Math.min(1,(index+1)/Math.max(1,c.samples*.92)),zones=c.zones;if(c.mode===4){const P=index===0?[...zones.P.target]:samp(zones.P,radius,rng),Q=index===0?[...zones.Q.target]:samp(zones.Q,radius,rng);const A=bisector(index===0?zones.A.target:samp(zones.A,radius,rng),P,c),D=bisector(index===0?zones.D.target:samp(zones.D,radius,rng),Q,c);if(!A||!D)return null;return {A,D,P,Q};}
 const pts={};for(const k of ['A','D','P','Q'])pts[k]=index===0?[...zones[k].target]:samp(zones[k],radius,rng);const seed=c.demoAngles||[c.angle*PI/180*.8,c.angle*PI/180*.45,c.angle*PI/180*.65],spread=PI*Math.sqrt(radius);const alpha=seed[0]+(index===0?0:(rng()-.5)*2*spread),beta=seed[1]+(index===0?0:(rng()-.5)*2*spread),gamma=seed[2]+(index===0?0:(rng()-.5)*2*spread);return candidate6(c,pts,alpha,beta,gamma);}
function validate(c){if(![4,6].includes(c.mode))throw Error('Select a supported topology.');for(const k of ['angle','dx','dy','minLength','maxLength','minTransmission','poseTolerance','angleTolerance','samples'])if(!Number.isFinite(c[k]))throw Error('Invalid '+k);if(Math.abs(c.angle)<1||Math.abs(c.angle)>175)throw Error('Target rotation must be between 1° and 175° in magnitude.');if(c.samples<1||c.samples>300000)throw Error('Samples must be between 1 and 300,000.');if(c.maxLength<=c.minLength||c.minLength<=0)throw Error('Check link length limits.');if(c.minTransmission<0||c.minTransmission>=1)throw Error('Transmission sine limit must be from 0 up to 1.');if(c.body.width<=0||c.body.height<=0)throw Error('Moving-body dimensions must be positive.');if(!Array.isArray(c.reference)||c.reference.some(x=>!Number.isFinite(x)))throw Error('Invalid reference point.');for(const k of c.mode===4?['A','D','P','Q']:['A','D','B','C','E','P','Q']){const z=c.zones[k];if(!z||!Number.isFinite(z.radius)||z.radius<0||z.target.length!==2||z.target.some(x=>!Number.isFinite(x)))throw Error('Invalid pivot '+k);}if(c.obstacles?.some(poly=>poly.length<3||poly.some(pt=>pt.length!==2||pt.some(v=>!Number.isFinite(v)))))throw Error('Invalid obstacles.');}
function candidateValid(p,c){if(!p||!Number.isFinite(scoreTargets(p,c.zones))||dist(p.A,p.D)<c.minLength)return false;if(c.mode===4)return checkLengths([[p.A,p.P],[p.D,p.Q],[p.P,p.Q],[p.A,p.D]],c)&&Math.abs(cross(sub(p.P,p.A),sub(p.Q,p.P)))>c.minLength;return checkLengths([[p.A,p.B],[p.A,p.E],[p.B,p.E],[p.D,p.C],[p.B,p.C],[p.B,p.P],[p.C,p.P],[p.E,p.Q],[p.P,p.Q]],c)&&Math.abs(cross(sub(p.B,p.A),sub(p.E,p.A)))>c.minLength&&Math.abs(cross(sub(p.C,p.B),sub(p.P,p.B)))>c.minLength;}
function evaluate(p,c){if(!candidateValid(p,c))return null;const sim=c.mode===4?simulate4(p,c):simulate6(p,c);if(!sim)return null;return {points:p,score:scoreCandidate(p,sim,c),...sim};}
function search(c,callback=()=>{},cancel=()=>false){validate(c);const rng=seedRandom(c.seed||12345),keep=[];let checked=0,valid=0;for(let i=0;i<c.samples;i++){if(cancel())break;const candidate=candidateAt(c,i,rng);checked++;const result=evaluate(candidate,c);if(result){valid++;if(keep.length<8||result.score<keep[keep.length-1].score){keep.push(result);keep.sort((a,b)=>a.score-b.score);if(keep.length>8)keep.pop();}}if(i%1000===0||i===c.samples-1)callback({checked,valid,results:keep});}return {checked,valid,results:keep};}
root.Linkage={pose,intersections,simulate4,simulate6,candidate6,candidateAt,evaluate,search,validate,seedRandom,wrap,rot,add,sub};if(typeof module!=='undefined')module.exports=root.Linkage;
if(typeof root.postMessage==='function'&&typeof root.document==='undefined')root.onmessage=ev=>{if(ev.data?.action!=='search')return;try{const result=search(ev.data.config,p=>root.postMessage({type:'progress',...p}));root.postMessage({type:'complete',...result});}catch(error){root.postMessage({type:'error',message:String(error.message||error)});}};
})(typeof self!=='undefined'?self:globalThis);
